controller_list:
  - name: fake_pmb2_gripper_controller
    joints:
      - motor1_hand_joint
      - motor2_hand_joint
  - name: fake_pmb2_arm_column_controller
    joints:
      - palbator_arm_column_joint
      - palbator_arm_shoulder_1_joint
      - palbator_arm_shoulder_2_joint
      - palbator_arm_shoulder_3_joint
      - palbator_arm_wrist_1_joint
      - palbator_arm_wrist_2_joint
      - palbator_arm_wrist_3_joint
initial:  # Define initial robot poses.
  - group: pmb2_gripper
    pose: close_gripper
  - group: pmb2_arm_column
    pose: travelling_pose