# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  hand1_fingertip1_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  hand1_fingertip2_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  hand2_fingertip1_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  hand2_fingertip2_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  motor1_hand_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  motor2_hand_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
  palbator_arm_column_joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: false
    max_acceleration: 0
  palbator_arm_shoulder_1_joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: false
    max_acceleration: 0
  palbator_arm_shoulder_2_joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: false
    max_acceleration: 0
  palbator_arm_shoulder_3_joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: false
    max_acceleration: 0
  palbator_arm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: false
    max_acceleration: 0
  palbator_arm_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: false
    max_acceleration: 0
  palbator_arm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 0.3
    has_acceleration_limits: false
    max_acceleration: 0