# Independent settings for the planner's costmap
global_costmap:
  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: obstacle_laser_layer
      type: 'costmap_2d::ObstacleLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'


  #global_costmap:
  #plugins:
  #  - name: obstacle_laser_layer
  #    type: 'costmap_2d::ObstacleLayer'
  #  - name: static_layer
  #    type: 'costmap_2d::StaticLayer'
  #  - name: obstacle_pcl_layer
  #    type: 'costmap_2d::ObstacleLayer'
  #  - name: inflation_layer
  #    type: 'costmap_2d::InflationLayer'
