# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap

  global_frame    : map
  robot_base_frame: base_footprint

  update_frequency : 10.0
  publish_frequency: 1.0

  transform_tolerance: 0.2

  track_unknown_space: true
  unknown_cost_value : 255

  robot_radius: 0.245 #0.275

  #plugins are loaded on a separate file

  static_layer:
    enabled  : true
    map_topic: map

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan pcl_scan_3
    combination_method: 0 # can erase static layer
    footprint_clearing_enabled: true

    base_scan:
      sensor_frame: base_laser_link
      data_type: LaserScan
      topic: scan
      expected_update_rate: 0.5
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

    pcl_scan_3:
      data_type: PointCloud2
      topic: /camera_base/depth/points
      marking: true
      clearing: true
      observation_persistence: 0.0
      track_unknown_space: true
      min_obstacle_height: 0.005
      max_obstacle_height: 2.0
      obstacle_range: 1.5
      raytrace_range: 2.5
      inf_is_valid: true

  #obstacle_sonar_layer:
  #  enabled: false
  #  ns: ""
  #  topics: ["/sonar_base"]
  #  no_readings_timeout: 0.0
  #  clear_threshold: 0.20
  #  mark_threshold: 0.80
  #  clear_on_max_reading: true

  #obstacle_pcl_layer:
  #  enabled: false
  #  footprint_clearing_enabled: true
  #  observation_sources: pcl_scan
  #  combination_method: 1 #0 can erase static layer, 1 maximum value is kept
  #  
  #  pcl_scan:
  #   data_type: PointCloud2
  #   topic: /camera_base/depth/points
  #   marking: true
  #   clearing: true
  #   #observation_persistence: 1.0
  #   track_unknown_space: false
  #   min_obstacle_height: 0.01
  #   max_obstacle_height: 0.2
  #   obstacle_range: 1.5
  #   raytrace_range: 2.5
  #   inf_is_valid: true
  #   blanking_range: 0.1
  #   expected_update_rate: 0.5
  #   observation_persistence: 0.0


  inflation_layer:
    enabled            : true
    inflation_radius   : 0.55
    cost_scaling_factor: 25.0
